# RichEditorNET Build Script

.build_template:
    before_script:
      - "git clean -fdxq"
      - "pwsh -f ./ReplaceVersion.ps1"

.publish_template:
    before_script:
      - "git clean -fdxq"
      - "dotnet tool install --global --prerelease sign"
      - "pwsh -f ./ReplaceVersion.ps1"
      - "az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID"
      - "az account set --subscription $AZURE_SUBSCRIPTION"
    after_script:
      - "az logout"

stages:
  - build
  - publish
  - post

Build RichEditorNET Package:
  extends: .build_template
  stage: build
  tags:
    - linux
    - dotnet
  only:
    refs:
      - dev
    changes:
      - .gitlab-ci.yml
      - RichEditorNET/**/*

  script:
    - "dotnet restore ./RichEditorNET/RichEditorNET.csproj"
    - "dotnet build -c Release ./RichEditorNET/RichEditorNET.csproj"

Publish RichEditorNET Package:
  extends: .publish_template
  stage: publish
  tags:
    - windows
    - dotnet
  only:
    refs:
      - master
    changes:
      - .gitlab-ci.yml
      - RichEditorNET/**/*

  script:
    - "dotnet restore ./RichEditorNET/RichEditorNET.csproj"
    - "dotnet build -c Release ./RichEditorNET/RichEditorNET.csproj"
    - "dotnet nuget push '.\\RichEditorNET\\bin\\Release\\*.nupkg' -s \"https://api.nuget.org/v3/index.json\" -k $NUGET_TOKEN --skip-duplicate"

Increment Build Counter:
  stage: post
  tags:
    - linux
    - dotnet
  only:
    refs:
      - master
    changes:
      - .gitlab-ci.yml
      - RichEditorNET/**/*

  script:
    - "pwsh -f ./IncrementVersion.ps1"
